replicaCount: 2

image:
  repository: 062370280028.dkr.ecr.eu-north-1.amazonaws.com/my-app-repo
  tag: latest
  pullPolicy: Always

containerPort: 5000

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"

ingress:
  enabled: true
  host: ""  
  path: /
  className: nginx

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""    

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

